/* generated by pull.js */
const manifest = {
  "editorOnly": true,
  "name": "Anarchy mode",
  "description": "Connect any block into any input.",
  "tags": ["new", "beta"],
  "credits": [
    {
      "name": "LilyMakesThings",
      "link": "https://scratch.mit.edu/users/LilyMakesThings/"
    }
  ],
  "dynamicDisable": false,
  "userscripts": [
    {
      "url": "anarchy.js"
    }
  ]
};
export default manifest;
