/* generated by pull.js */
import _js from "./userscript.js";
import _asset from "!url-loader!./icon--mute.svg";
import _asset2 from "!url-loader!./mute.svg";
export const resources = {
  "userscript.js": _js,
  "icon--mute.svg": _asset,
  "mute.svg": _asset2,
};
